### ISSUE TITLE
Advanced searching

### ISSUE THREAD

**Issue by kmanpro** [shmsoft/FreeEedUI#29]
How do you do complex queries using the freeEedReview interface?

I tried the following and it seemed to add more results to the pool instead of reducing.

This one came back with 21377 results 

> information

 

And this one came back with 34213 results

> information AND doctor

I would expect the AND search to be less than the first not more.

What is the correct syntax for AND Boolean searching?
I thought it was lucene but it appears that is not the case?

Thanks!

**Comment by farshidmh** [comment]
You don't need to write binary terms.

keywords are searched with **and** condition.

so in your case search for **information** then search for **doctor**

**Comment by farshidmh** [comment]
![Capture](https://user-images.githubusercontent.com/53330886/69564354-1f3a1f00-0fc8-11ea-8d0f-ce970ef07c8a.JPG)
you should see something like this

**Comment by kmanpro** [comment]
Thank you for your response!
How about for field searching? Such as to: or from:?

Is there anyway to input a raw lucene query?

**Comment by markkerzner** [comment]
I added the "Help" link to the search UI
